const DIRECT_DEBIT_CHANNEL = {
    DIRECT_DEBIT_ALLO_SNAP : "DIRECT_DEBIT_ALLO_SNAP",
    DIRECT_DEBIT_CIMB_SNAP : "DIRECT_DEBIT_CIMB_SNAP",
    DIRECT_DEBIT_MANDIRI_SNAP : "DIRECT_DEBIT_MANDIRI_SNAP",
    DIRECT_DEBIT_BRI_SNAP : "DIRECT_DEBIT_BRI_SNAP",
    EMONEY_OVO_SNAP : "EMONEY_OVO_SNAP",
    EMONEY_SHOPEE_PAY_SNAP : "EMONEY_SHOPEE_PAY_SNAP",
    EMONEY_DANA_SNAP : "EMONEY_DANA_SNAP",
};

Object.freeze(DIRECT_DEBIT_CHANNEL); // This ensures the enum values are immutable

module.exports = DIRECT_DEBIT_CHANNEL;