const V2_CHANNEL_TO_V1 = {
    "VIRTUAL_ACCOUNT_DOKU": "47",
    "VIRTUAL_ACCOUNT_SINARMAS": "22",
    "VIRTUAL_ACCOUNT_BANK_MANDIRI": "41",
    "VIRTUAL_ACCOUNT_MAYBANK": "44",
    "VIRTUAL_ACCOUNT_SINARMAS_FULL": "21",
    "VIRTUAL_ACCOUNT_QNB": "42",
    "VIRTUAL_ACCOUNT_BTN": "43",
    "VIRTUAL_ACCOUNT_BRI": "34",
    "VIRTUAL_ACCOUNT_BANK_MANDIRI": "08",
    "VIRTUAL_ACCOUNT_BCA": "29",
    "VIRTUAL_ACCOUNT_BNI": "40",
    "VIRTUAL_ACCOUNT_BNI": "38",
    "VIRTUAL_ACCOUNT_BANK_DANAMON": "33",
    "VIRTUAL_ACCOUNT_BANK_PERMATA": "07",
    "VIRTUAL_ACCOUNT_BANK_CIMB": "32",
    "VIRTUAL_ACCOUNT_BANK_PERMATA": "05",
    "VIRTUAL_ACCOUNT_BANK_PERMATA": "36",
    "VIRTUAL_ACCOUNT_BANK_MANDIRI": "09"
  };
Object.freeze(V2_CHANNEL_TO_V1); // This ensures the enum values are immutable

module.exports = V2_CHANNEL_TO_V1;